application: thevoice-on-itunes
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: thevoice-on-itunes.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
